FROM python:3.13.9-alpine3.22

RUN pip install pandas numpy matplotlib pyarrow

ADD containers/Analysis/entrypoint.sh /

ADD src/python/MakeComEdDataFrame.py /
ADD src/python/MakeEnphaseDataFrame.py /
ADD src/python/MakeEmporiaDataFrame.py /

ADD src/python/ComedAnalysis.py /
ADD src/python/EnphaseAnalysis.py /
ADD src/python/EmporiaAnalysis.py /
ADD src/python/MonthlyCost.py /

ADD containers/Analysis/delivery.json /

ENTRYPOINT /entrypoint.sh
