kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: enphase-pvc
  namespace: solar-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: auto-ebs-sc

