apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: solar-monitoring
  name: enphase-token
spec:
  schedule: "1 */12 * * *"  # Every 12 hours
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: enphase-token
        spec:
          restartPolicy: OnFailure
          containers:
            - name: enphase-test
              image: ericvaandering/solar-monitoring:0.0.1
              imagePullPolicy: Always
              volumeMounts:
                - name: enphase-data
                  mountPath: /var/lib/enphase
              env:
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    key: enphase_api_key
                    name: enphase-secrets
              - name: AUTH_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    key: enphase_credentials
                    name: enphase-secrets
          volumes:
            - name: enphase-data
              persistentVolumeClaim:
                claimName: enphase-pvc